### ISSUE TITLE
Update maven dependency in readme

### ISSUE THREAD

**Issue by planetlevel** [Contrast-Security-OSS/contrast-sdk-java#10]
The maven dependency needs to be updated

		<dependency>
			<groupId>com.contrastsecurity</groupId>
			<artifactId>contrast-sdk-java</artifactId>
			<version>2.1.3-SNAPSHOT</version>
		</dependency>

Also, please update with an example of ContrastSDK instead of ContrastConnection.  Something like...

        contrastSDK = new ContrastSDK("test@test.com", "testApiKey", "testServiceKey", "https://apptwo.contrastsecurity.com/Contrast/api");

        String org = sdk.getProfileDefaultOrganizations().getOrganization().getOrgUuid();

        Applications apps = sdk.getApplications( org );
        for ( Application app : apps.getApplications() ) {
            System.out.println( app.getName() + " (" + app.getCodeShorthand() + " LOC)" );
        }

Output:

        Aneritx (48K LOC)
        Default Web Site (0k LOC)
        EnterpriseTPS (48K LOC)
        Feynmann (48K LOC)
        jhipster-sample (0k LOC)
        JSPWiki (48K LOC)
        Liferay (48K LOC)
        OpenMRS (65K LOC)
        OracleFS (48K LOC)
        Security Test (< 1K LOC)
        Ticketbook (2K LOC)
        WebGoat (48K LOC)
        WebGoat7 (106K LOC)

**Comment by gmoore** [comment]
Updated README!
