### ISSUE TITLE
CONTRAST: Hardcoded Password  in SpringInputPasswordFieldAttrProcessor.java

### ISSUE THREAD

**Issue by kristianamitchellcontrastsecurity** [Contrast-Security-OSS/contrast-sdk-java#40]
**Vulnerability ID**: 62E4-P4HI-FXMG-RXXJ

**Application Name**: WebGoat

**Vulnerability Link**: http://localhost:19080/Contrast/static/ng/index.html#/1eff1e07-1036-494f-b354-8155b348a837/applications/5bbf636c-e180-4cd6-bf6e-cfee0e2c3645/vulns/62E4-P4HI-FXMG-RXXJ

## What Happened?
The "PASSWORD_INPUT_TYPE_ATTR_VALUE" field in SpringInputPasswordFieldAttrProcessor.java (org.thymeleaf.spring4.processor.attr.SpringInputPasswordFieldAttrProcessor) looks like a hardcoded password:

public&nbsp;static&nbsp;String&nbsp;PASSWORD_INPUT_TYPE_ATTR_VALUE&nbsp;=&nbsp;&quot;[hidden]&quot;;

## What's the risk?
Hardcoded passwords are a dangerous practice for a few reasons.

First, having passwords in source code implicitly gives backend system access to anyone with access to the code repository or built binaries. Given the history of source code disclosure flaws in server software, and the possibility of compromise when using cloud-based source code repositories, assuming attacker access to your source code is a prudent philosophy.

Second, hardcoded passwords make responding to security events more difficult. If a backend password needs to be rotated, a new build must be elevated to compensate. If the value is pulled from a configuration file instead, the operations team can respond nearly instantaneously.

## Recommendation
The password detected should be taken out of source code and made available via configuration
management. An encrypted properties file like the one provided by ESAPI would allow the code to 
be taken out of the source code and be provided environment-specific values.

Alternatively, the value could be taken from System properties.

## First Event
``````(no event)``````

## Last Event
``````(no event)``````

## HTTP Request
(No HTTP Request)

## References
https://www.securecoding.cert.org/confluence/display/java/MSC03-J.+Never+hard+code+sensitive+information

**Comment by gilday** [comment]
@kristianamitchellcontrastsecurity can we use a different repo for this? I keep getting these vulnerability issue notifications, but I don't think the vulnerability applies to this code base

**Comment by kristianamitchellcontrastsecurity** [comment]
yes sorry i did it once as a practice and thought i unlinked it! thank you for alerting me @gilday
