### ISSUE TITLE
The last two releases are missing from Maven Central

### ISSUE THREAD

**Issue by sethjackson** [Contrast-Security-OSS/contrast-sdk-java#77]
The last two releases (`contrast-sdk-java-3.0` and `contrast-sdk-java-3.1`) are missing from Maven Central.
Can these please be uploaded? Thanks!

**Comment by pprofili-contrast** [comment]
Thanks, @sethjackson , we had a little issue with the pipeline that we're working on addressing now

**Comment by sethjackson** [comment]
Thanks @pprofili-contrast! Any idea when the latest versions might get pushed to Maven Central?

**Comment by pprofili-contrast** [comment]
"Stuck in legal" is what they tell me 😞

**Comment by gilday** [comment]
We expect to resolve this soon.

**Comment by sethjackson** [comment]
Awesome! :)

**Comment by gilday** [comment]
https://repo1.maven.org/maven2/com/contrastsecurity/contrast-sdk-java/3.3/
